name: Rust CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: engine
    steps:
      - name: Set up Rust
        uses: actions/checkout@v2
      - name: Install cargo-audit
        run: cargo install cargo-audit
      - name: Install libs
        run: sudo apt-get install -y libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgl1-mesa-dev
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
      - name: Clippy
        run: cargo clippy --verbose -- -D warnings
      - name: Audit
        run: cargo audit